/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vw3g7JYC3Jm
 */
import Image from "next/image"

export function BookList() {
  return (
    <div className="bg-white p-8">
      <div className="mb-4 text-sm">
        <a className="text-blue-600 hover:underline" href="#">
          Add Send.cm Direct Link to test. Any suggestions? contact me.
        </a>
      </div>
      <div className="flex justify-between">
        <div className="w-3/5">
          <h1 className="text-2xl font-bold mb-4">All Books</h1>
          <div className="flex items-center mb-4">
            <label className="mr-2" htmlFor="sort">
              Sort by
            </label>
            <select className="border border-gray-300 rounded px-2 py-1" id="sort">
              <option>Post Date (Default)</option>
              <option>Popularity</option>
              <option>Rating</option>
              <option>Alphabetical</option>
            </select>
          </div>
          <div className="space-y-6">
            <div className="border rounded p-4">
              <div className="flex items-start space-x-4">
                <Image
                  alt="Book cover"
                  className="w-24 h-32 object-cover"
                  height="120"
                  src="/placeholder.svg"
                  width="90"
                />
                
                <div>
                  <h2 className="text-lg font-bold">{`Books About Python Coding: Beginner's`}</h2>
                  <p className="text-sm text-gray-600">by Kartik Bheel</p>
                  <p className="text-sm">Length: 54 pages</p>
                  <p className="text-sm">Publication Date: 2024-03-10</p>
                  <div className="flex items-center mt-2">
                    <span className="text-yellow-400 text-sm">★★★★★</span>
                    <span className="text-gray-500 text-xs ml-2">(0)</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="border rounded p-4">
              <div className="flex items-start space-x-4">
                <Image
                  alt="Book cover"
                  className="w-24 h-32 object-cover"
                  height="120"
                  src="/placeholder.svg"
                  width="90"
                />
                
                <div>
                  <h2 className="text-lg font-bold">Advanced Vuejs with examples</h2>
                  <p className="text-sm text-gray-600">by Carlo Zuffetti</p>
                  <p className="text-sm">Length: 81 pages</p>
                  <p className="text-sm">Publication Date: 2024-03-10</p>
                  <div className="flex items-center mt-2">
                    <span className="text-yellow-400 text-sm">★★★★★</span>
                    <span className="text-gray-500 text-xs ml-2">(0)</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="border rounded p-4">
              <div className="flex items-start space-x-4">
                <Image
                  alt="Book cover"
                  className="w-24 h-32 object-cover"
                  height="120"
                  src="/placeholder.svg"
                  width="90"
                />
                
                <div>
                  <h2 className="text-lg font-bold">
                    Becoming an Expert in 3ds Max A Comprehensive Guide to Mastering 3D Design and Animation: Become
                    Expert In 3D...
                  </h2>
                  <p className="text-sm text-gray-600">by Suzy Suson</p>
                  <p className="text-sm">Length: 72 pages</p>
                  <p className="text-sm">Publication Date: 2024-03-10</p>
                  <div className="flex items-center mt-2">
                    <span className="text-yellow-400 text-sm">★★★★★</span>
                    <span className="text-gray-500 text-xs ml-2">(0)</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="border rounded p-4">
              <div className="flex items-start space-x-4">
                <Image
                  alt="Book cover"
                  className="w-24 h-32 object-cover"
                  height="120"
                  src="/placeholder.svg"
                  width="90"
                />
                
                <div>
                  <h2 className="text-lg font-bold">
                    ChatGPT & AI Skills: Securing Your Job in 2024: Earn Money with Artificial Intelligence Basic:
                    AI-Powered Productivity: AI...
                  </h2>
                  <p className="text-sm text-gray-600">by Maryna Biloidid</p>
                  <p className="text-sm">Length: 94 pages</p>
                  <p className="text-sm">Publication Date: 2024-03-10</p>
                  <div className="flex items-center mt-2">
                    <span className="text-yellow-400 text-sm">★★★★★</span>
                    <span className="text-gray-500 text-xs ml-2">(0)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="w-1/4 ml-8">
          <div className="mb-6">
            <h2 className="text-lg font-bold mb-2">Hot searches</h2>
            <div className="space-y-1">
              <a className="text-blue-600 hover:underline" href="#">
                Python
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Flutter
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Golang
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Rust
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                React
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                JavaScript
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Django
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Kotlin
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Java
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Kubernetes
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Linux
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Azure
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                .NET Core
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Spring
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Vue
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                TypeScript
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                AWS
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Vim
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                Angular
              </a>
              <a className="text-blue-600 hover:underline" href="#">
                C++
              </a>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-bold mb-2">Hot books of the week</h2>
            <ol className="list-decimal list-inside">
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Analyzing Blockchain in Healthcare: Applications and Methodologies
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Programming in C Part Two: Advanced Data Structures
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Grokking Algorithms, 2nd Edition
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Becoming SRE: First Steps Toward Reliability
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Computer Architecture: From the Stone Age to the Silicon Age
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Code Like a Pro in Rust
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  An Introduction to PHP: Learn PHP 8 to Code Websites
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Effective Machine Learning Teams: Best Practices
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  AWS Certified Solutions Architect - Professional Study Guide
                </a>
              </li>
              <li>
                <a className="text-blue-600 hover:underline" href="#">
                  Learn C++ by Example: Covers versions 11, 14, 17, and 20
                </a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  )
}
